import { StyleSheet, Dimensions, Platform } from 'react-native';

const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.9)',
    },
    safeContainer: {
        flex: 1,
    },
    gradient: {
        flex: 1,
        paddingBottom: Platform.OS === 'ios' ? 85 : 60,
    },
    header: {
        alignItems: 'center',
        paddingTop: Platform.OS === 'ios' ? 60 : screenWidth * 0.08,
        paddingBottom: screenWidth * 0.05,
    },
    profileImage: {
        width: screenWidth * 0.25,
        height: screenWidth * 0.25,
        borderRadius: screenWidth * 0.125,
        borderWidth: 2,
        borderColor: '#4ECDC4',
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: "center",
        paddingHorizontal: screenWidth * 0.05,
        paddingBottom: Platform.OS === 'ios' ? 20 : 0,
    },
    infoContainer: {
        width: '100%',
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 15,
        padding: screenWidth * 0.04,
        marginTop: screenWidth * 0.03,
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: screenWidth * 0.03,
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 12,
        padding: screenWidth * 0.035,
    },
    infoIconContainer: {
        width: screenWidth * 0.11,
        height: screenWidth * 0.11,
        borderRadius: screenWidth * 0.055,
        backgroundColor: 'rgba(78, 205, 196, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: screenWidth * 0.03,
    },
    infoTextContainer: {
        flex: 1,
    },
    infoTitle: {
        fontSize: screenWidth * 0.035,
        fontWeight: '600',
        color: '#4ECDC4',
        marginBottom: screenWidth * 0.01,
    },
    infoText: {
        fontSize: screenWidth * 0.042,
        color: '#fff',
        fontWeight: '500',
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(78,205,196,0.15)',
        borderRadius: 12,
        padding: screenWidth * 0.035,
        marginTop: screenWidth * 0.03,
    },
    editButtonText: {
        color: '#4ECDC4',
        fontSize: screenWidth * 0.04,
        fontWeight: '600',
        marginLeft: screenWidth * 0.02,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: screenWidth * 0.04,
    },
    actionButton: {
        backgroundColor: 'rgba(78,205,196,0.15)',
        borderRadius: 12,
        padding: screenWidth * 0.035,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '48%',
    },
    actionButtonText: {
        color: '#4ECDC4',
        fontSize: screenWidth * 0.035,
        fontWeight: '600',
        marginLeft: screenWidth * 0.02,
    },
    longButton: {
        backgroundColor: '#4ECDC4',
        borderRadius: 12,
        padding: screenWidth * 0.04,
        marginTop: screenWidth * 0.04,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    longButtonText: {
        fontSize: screenWidth * 0.04,
        fontWeight: '700',
        color: '#000',
        textTransform: 'uppercase',
        letterSpacing: 1,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    chatbotButton: {
        width: screenWidth * 0.15,
        height: screenWidth * 0.15,
        borderRadius: screenWidth * 0.075,
        alignSelf: 'center',
        marginTop: screenWidth * 0.04,
        marginBottom: Platform.OS === 'ios' ? 10 : screenWidth * 0.05,
        overflow: 'hidden',
        elevation: 8,
        shadowColor: '#4ECDC4',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
    },
    chatbotButtonGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: '#4ECDC4',
        borderRadius: screenWidth * 0.075,
    },
    aboutModalContent: {
        flex: 1,
        padding: screenWidth * 0.05,
        paddingTop: Platform.OS === 'ios' ? screenWidth * 0.1 : screenWidth * 0.05,
    },
    welcomeSection: {
        borderRadius: 15,
        padding: screenWidth * 0.05,
        marginBottom: screenWidth * 0.05,
    },
    aboutModalSubtitle: {
        fontSize: screenWidth * 0.045,
        fontWeight: '600',
        color: '#4ECDC4',
        marginBottom: screenWidth * 0.04,
        textAlign: 'center',
    },
    aboutModalText: {
        fontSize: screenWidth * 0.035,
        color: '#fff',
        lineHeight: screenWidth * 0.05,
        marginBottom: screenWidth * 0.04,
    },
    developerSection: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
    },
    featuresTitle: {
        fontSize: screenWidth * 0.05,
        fontWeight: 'bold',
        color: '#4ECDC4',
        marginBottom: 20,
        marginTop: 10,
        textAlign: 'center',
    },
    featuresContainer: {
        marginBottom: 20,
    },
    featureCard: {
        flexDirection: 'row',
        borderRadius: 15,
        padding: 15,
        marginBottom: 15,
        alignItems: 'flex-start',
    },
    featureIconContainer: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: 'rgba(78,205,196,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    featureTextContainer: {
        flex: 1,
    },
    featureTitle: {
        fontSize: screenWidth * 0.04,
        fontWeight: 'bold',
        color: '#4ECDC4',
        marginBottom: 8,
    },
    featureDescription: {
        fontSize: screenWidth * 0.035,
        color: '#fff',
        opacity: 0.9,
        lineHeight: screenWidth * 0.05,
    },
    modalContent: {
        width: screenWidth * 0.9,
        borderRadius: 20,
        padding: 20,
        backgroundColor: 'rgba(0,0,0,0.9)',
    },
    inputContainer: {
        marginBottom: 20,
    },
    modalInput: {
        marginBottom: 15,
    },
    modalSaveButton: {
        marginTop: 10,
    },
    chatbotModalContent: {
        flex: 1,
        margin: 20,
        borderRadius: 20,
        overflow: 'hidden',
    },
    chatbotWelcomeSection: {
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
    },
    chatbotFeatureGrid: {
        marginBottom: 20,
    },
    chatbotFeatureRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    chatbotFeatureCard: {
        width: '48%',
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 15,
        padding: 15,
        alignItems: 'center',
    },
    chatbotFeatureIconContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(78,205,196,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    chatbotFeatureTitle: {
        fontSize: screenWidth * 0.04,
        fontWeight: 'bold',
        color: '#4ECDC4',
        marginBottom: 8,
        textAlign: 'center',
    },
    chatbotFeatureText: {
        fontSize: screenWidth * 0.035,
        color: '#fff',
        textAlign: 'center',
        opacity: 0.9,
    },
    chatbotCapabilitiesSection: {
        borderRadius: 15,
        padding: 20,
    },
    chatbotSectionTitle: {
        fontSize: screenWidth * 0.045,
        fontWeight: 'bold',
        color: '#4ECDC4',
        marginBottom: 15,
        textAlign: 'center',
    },
    chatbotCapabilitiesList: {
        marginTop: 10,
    },
    chatbotCapabilityItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    chatbotCapabilityText: {
        fontSize: screenWidth * 0.035,
        color: '#fff',
        marginLeft: 10,
        opacity: 0.9,
    },
}); 